# Aliases
alias nv=nvim
alias vim=nvim

# rust
. "$HOME/.cargo/env"

# oh-my-posh
eval "$(oh-my-posh init bash --config ~/.poshthemes/jblab_2021.omp.json)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

export XDG_DATA_DIRS=$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share

# env
export PATH=$PATH:$HOME/.local/bin

source /home/minhdao/Projects/alacritty/extra/completions/alacritty.bash
