import:
  - ~/Projects/alacritty-theme/themes/Mariana.yaml

font:
  normal:
    family: FiraMono Nerd Font
    style: Regular
  bold:
    family: FiraMono Nerd Font
    style: Bold
  italic:
    family: FiraMono Nerd Font
    style: Italic
  size: 12

cursor:
  style:
    shape: Beam
  unfocused_hollow: true
